import os
os.system("cls")

# Em linguagem C

idade = 30
if idade >= 18:
    print ("maior de idade")
    print ("menor de idade")
else:
    print ("a")
    print ("b")
print ("c")

# if else

x = 30
if x >= 18:
    print ("a")
    print ("a")
else:
    print ("a")
    print ("b")

# if elif else

x = 30
if x >= 18:
    print("b")
elif x > 30:
    print ("c")
elif x > 40:
    print ("d")
else:
    print ("e")